export FLASK_APP=nfl
export POSTGRES_DB=${POSTGRES_DB:-nfl}
export POSTGRES_USER=${POSTGRES_USER:-nfl}
export POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-nfl}
export POSTGRES_HOST=${POSTGRES_HOST:-localhost}
export POSTGRES_PORT=${POSTGRES_PORT:-5432}
